import { Entity, Fields } from "remult";

/**
 * One row per Seaquel installation — Cloud or self-hosted. Created on
 * the first `/api/cloud/register-install` call from a given installId,
 * then used by `requireCloudAuth` (in `cloud-auth.ts`) to verify that
 * every subsequent `/api/cloud/*` call from the install is presenting a
 * license key tied to the same Dodo subscription that registered it.
 *
 * Pairs with the `tenants` table:
 *   - For Cloud tenants, `tenantId === Tenant.id` and was created at
 *     provision time (existing tenants are backfilled by migration 0003).
 *   - For self-hosted installs, the control plane auto-creates a Tenant
 *     row on first registration so that members / bind / unbind / etc.
 *     can be handled uniformly. The synthetic tenant has
 *     `slug = "self-" + installId.slice(0, 8)`.
 *
 * `subscriptionId` is captured from the registering License's
 * `dodoSubscriptionId` at register time and never updated. Re-registering
 * the same installId under a different subscription is a conflict
 * (`install_subscription_mismatch`) — installs are pinned to a single
 * Dodo subscription for their lifetime.
 */
@Entity<Install>("installs", {
  // CRUD goes through `register-install` + `cloud-auth.ts` server-side;
  // there's no client-facing read path. Server-side repo calls bypass
  // these flags, so the REST endpoint stays fully closed.
  allowApiCrud: false,
})
export class Install {
  /**
   * The installId UUID minted on the seaquel side (one per install).
   * Acts as the row's primary key — `findId(installIdHdr)` is the hot
   * lookup on every authenticated `/api/cloud/*` request. Provided by
   * the caller (not auto-generated by Remult) so that the same install
   * can be re-registered idempotently after a control-plane wipe.
   */
  @Fields.string({ required: true, allowApiUpdate: false })
  id!: string;

  /**
   * Dodo subscription id of the license that registered this install.
   * Indexed for the future "cancel all installs for a subscription"
   * webhook path.
   */
  @Fields.string({ required: true, allowApiUpdate: false })
  subscriptionId = "";

  /**
   * The Tenant row this install belongs to. For Cloud installs this is
   * the provisioned tenant; for self-hosted installs it's the synthetic
   * `self-{prefix}` tenant auto-created at register time.
   */
  @Fields.string({ required: true, allowApiUpdate: false })
  tenantId = "";

  @Fields.createdAt({ allowApiUpdate: false })
  createdAt!: Date;
}
